import type { Certificate, Course } from './types';

export const coursesData: {
    certificates: Certificate[];
    courses: Course[];
    specializations: Certificate[];
} = {
    certificates: [
        {
            id: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'DevOps Pro: Linux, Docker, Kubernetes, CI/CD & IaC',
            category: 'Specialization',
            status: 'in-progress',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            date: '2026-10-05',
            skills: [
                'DevOps',
                'Linux',
                'Docker',
                'Kubernetes',
                'CI/CD',
                'Infrastructure as Code (IaC)',
                'Git',
                'Terraform',
                'Automation',
            ],
            credentialUrl:
                'https://www.coursera.org/specializations/devops-linux-docker-kubernetes-ci-cd-iac',
            credential: '',
            image: '',
            logo: '/assets/images/logo/kodekloud.png',
        },
        {
            id: 'ibm-introduction-to-data-science',
            title: 'Introduction to Data Science',
            category: 'Specialization',
            status: 'in-progress',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-10-01',
            skills: [
                'Data Science',
                'Python',
                'SQL',
                'Relational Databases (RDBMS)',
                'Data Science Methodology',
                'Data Analysis',
                'Jupyter Notebooks',
            ],
            credentialUrl:
                'https://www.coursera.org/specializations/introduction-data-science',
            credential: '',
            image: '',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'applied-cryptography',
            title: 'Applied Cryptography',
            category: 'Specialization',
            provider: 'University of Colorado System',
            issuer: 'Coursera',
            date: '2026-09-30',
            skills: [
                'Cryptography',
                'Symmetric Cryptography',
                'Asymmetric Cryptography',
                'Key Management',
                'Hash Functions',
                'Digital Signatures',
                'Information Security',
                'PKI',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/specialization/YZ072EU527OF',
            credential: 'YZ072EU527OF',
            image: '/assets/certificates/Applied Cryptography Specialization.jpg',
            logo: '/assets/images/logo/cu.svg',
        },
        {
            id: 'google-project-management',
            title: 'Google Project Management',
            category: 'Professional Certificate',
            provider: 'Google',
            issuer: 'Coursera',
            date: '2026-10-05',
            skills: [
                'Project Management',
                'Agile Project Management',
                'Scrum',
                'Project Planning',
                'Risk Management',
                'Project Execution',
                'Stakeholder Management',
                'Work Breakdown Structure (WBS)',
                'Sprint Planning',
                'Quality Management',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/JXAEXEO4XLGR',
            credential: 'JXAEXEO4XLGR',
            image: '/assets/certificates/Google Project Management Professional.jpg',
            logo: '/assets/images/logo/google.svg',
        },
        {
            id: 'ibm-machine-learning',
            title: 'IBM Machine Learning',
            category: 'Professional Certificate',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'Machine Learning',
                'Python',
                'Supervised Learning',
                'Unsupervised Learning',
                'Neural Networks',
                'Deep Learning',
                'Regression',
                'Classification',
                'Clustering',
                'Reinforcement Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/G9QD5BA2LI68',
            credential: 'G9QD5BA2LI68',
            image: '/assets/certificates/IBM Machine Learning.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'ibm-introduction-to-machine-learning',
            title: 'IBM Introduction to Machine Learning',
            category: 'Specialization',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'Machine Learning',
                'Exploratory Data Analysis',
                'Supervised Learning',
                'Unsupervised Learning',
                'Linear Regression',
                'Classification',
                'Python',
                'Scikit-learn',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/specialization/C1ITBGE5WI0Z',
            credential: 'C1ITBGE5WI0Z',
            image: '/assets/certificates/IBM Introduction to Machine Learning.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
                {
            id: 'ibm-devops-software-engineering',
            title: 'IBM DevOps and Software Engineering',
            category: 'Professional Certificate',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'DevOps',
                'Software Engineering',
                'CI/CD',
                'Agile Methodologies',
                'Linux',
                'Git',
                'Docker',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/1OVGPIEULHS5',
            credential: '1OVGPIEULHS5',
            image: '/assets/certificates/IBM DevOps and Software Engineering.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'ibm-ai-foundations-for-everyone',
            title: 'AI Foundations for Everyone',
            category: 'Specialization',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-09-25',
            skills: [
                'Artificial Intelligence (AI)',
                'Generative AI',
                'Prompt Engineering',
                'Chatbots',
                'IBM Watson',
                'Machine Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/specialization/7VNLDPYRA9M2',
            credential: '7VNLDPYRA9M2',
            image: '/assets/certificates/IBM AI Foundations for Everyone Specialization.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'pimnas-peserta',
            title: 'Peserta Pekan Ilmiah Mahasiswa Nasional (PIMNAS) 2025',
            category: 'Competition & Award',
            provider: 'Kemdiktisaintek',
            issuer: 'Belmawa',
            date: '2025-12-04',
            skills: [
                'PKM-KI',
                'Kesehatan',
                'IoT',
                'Penelitian',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/PESERTA-PIMNAS.jpg',
            logo: '/assets/images/logo/kemendikbud.svg',
        },
        {
            id: 'pimnas-pendanaan',
            title: 'Peraih Pendanaan & Finalis PIMNAS PKM-KI 2025',
            category: 'Competition & Award',
            provider: 'Kemdiktisaintek',
            issuer: 'Belmawa',
            date: '2025-12-04',
            skills: [
                'PKM-KI',
                'Karya Inovatif',
                'Pendanaan',
                'Penelitian',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/PENDANAAN-PKM.jpg',
            logo: '/assets/images/logo/kemendikbud.svg',
        },
        {
            id: 'bnsp-web-developer',
            title: 'Sertifikat  Kompetensi – Web Developer',
            category: 'Competency Certificate',
            provider: 'Badan Nasional Sertifikat Profesi (BNSP)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2025-01-28',
            skills: [
                'Web Programming',
                'Frontend',
                'Backend',
                'Sertifikat BNSP',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/bnsp-web-developer.png',
            logo: '/assets/images/logo/logo-bnsp.png',
        },
        {
            id: 'bnsp-junior-mobile-programmer',
            title: 'Sertifikat  Kompetensi – Junior Mobile Programmer',
            category: 'Competency Certificate',
            provider: 'Badan Nasional Sertifikat Profesi (BNSP)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2024-09-17',
            skills: [
                'Mobile Programming',
                'Kotlin',
                'Android',
                'Sertifikat BNSP',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/bnsp-junior-mobile-developer.png',
            logo: '/assets/images/logo/logo-bnsp.png',
        },
        {
            id: 'apti-pemrograman-web',
            title: 'Sertifikat  Kompetensi Keahlian – Pemrograman Web',
            category: 'Competency Certificate',
            provider: 'Asosiasi Profesi Telematika Indonesia (APTI)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2024-01-22',
            skills: [
                'Web Programming',
                'Frontend',
                'Backend',
                'Sertifikat APTI',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/apti-web-programming.png',
            logo: '/assets/images/logo/logo-apti.png',
        },
    ],
    get specializations() {
        return this.certificates;
    },
    courses: [
        {
            id: 1,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Agile'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/PUUPJRYMVFWY',
            credential: 'PUUPJRYMVFWY',

            image: '/assets/courses/Coursera PUUPJRYMVFWY.jpg',
        },
        {
            id: 2,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Cloud Computing',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Cloud Computing', 'IaaS', 'PaaS', 'SaaS'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/KWII2E29GUCP',
            credential: 'KWII2E29GUCP',

            image: '/assets/courses/Coursera KWII2E29GUCP.jpg',
        },
        {
            id: 3,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Agile Development and Scrum',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Agile', 'Scrum', 'Sprint Planning', 'Kanban'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/B58WYKB58HX3',
            credential: 'B58WYKB58HX3',

            image: '/assets/courses/Coursera B58WYKB58HX3.jpg',
        },
        {
            id: 4,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Software Engineering',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Software Engineering', 'SDLC', 'UML', 'Design Patterns'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/9YNVBW6VFS74',
            credential: '9YNVBW6VFS74',

            image: '/assets/courses/Coursera 9YNVBW6VFS74.jpg',
        },
        {
            id: 5,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Getting Started with Git and GitHub',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Git', 'GitHub', 'Version Control', 'Branching'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/QU0UD8JBBN5Y',
            credential: 'QU0UD8JBBN5Y',

            image: '/assets/courses/Coursera QU0UD8JBBN5Y.jpg',
        },
        {
            id: 6,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Hands-on Introduction to Linux Commands and Shell Scripting',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Linux', 'Shell Scripting', 'Bash', 'Command Line'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/NTXSWHCXGP3M',
            credential: 'NTXSWHCXGP3M',

            image: '/assets/courses/Coursera NTXSWHCXGP3M.jpg',
        },
        {
            id: 7,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Python for Data Science, AI & Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Data Science', 'Pandas', 'NumPy'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/00CUZNBVXHAY',
            credential: '00CUZNBVXHAY',

            image: '/assets/courses/Coursera 00CUZNBVXHAY.jpg',
        },
        {
            id: 8,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Developing AI Applications with Python and Flask',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Flask', 'REST API', 'AI'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/N0Y5ATDNQA8A',
            credential: 'N0Y5ATDNQA8A',

            image: '/assets/courses/Coursera N0Y5ATDNQA8A.jpg',
        },
        {
            id: 9,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Containers w/ Docker, Kubernetes & OpenShift',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Docker', 'Kubernetes', 'OpenShift', 'Containers'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/X9VP7V6B22F2',
            credential: 'X9VP7V6B22F2',

            image: '/assets/courses/Coursera X9VP7V6B22F2.jpg',
        },
        {
            id: 10,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Application Development using Microservices and Serverless',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Microservices', 'Serverless', 'REST API', 'Cloud Native'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/9ZP2USR1M7WN',
            credential: '9ZP2USR1M7WN',

            image: '/assets/courses/Coursera 9ZP2USR1M7WN.jpg',
        },
        {
            id: 11,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Test and Behavior Driven Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['TDD', 'BDD', 'Testing', 'Python'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/COIY4WLZRL9Q',
            credential: 'COIY4WLZRL9Q',

            image: '/assets/courses/Coursera COIY4WLZRL9Q.jpg',
        },
        {
            id: 12,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Continuous Integration and Continuous Delivery (CI/CD)',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['CI/CD', 'Jenkins', 'DevOps', 'Automation'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/TKS66EQVG4WU',
            credential: 'TKS66EQVG4WU',

            image: '/assets/courses/Coursera TKS66EQVG4WU.jpg',
        },
        {
            id: 13,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Application Security for Developers and DevOps Professionals',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Security', 'DevSecOps', 'OWASP', 'Threat Modeling'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/GN3SHQZ0PIQT',
            credential: 'GN3SHQZ0PIQT',

            image: '/assets/courses/Coursera GN3SHQZ0PIQT.jpg',
        },
        {
            id: 14,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Monitoring and Observability for Development and DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Monitoring', 'Observability', 'Prometheus', 'Grafana'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/IOTESW68DTO6',
            credential: 'IOTESW68DTO6',

            image: '/assets/courses/Coursera IOTESW68DTO6.jpg',
        },
        {
            id: 15,
            certificateId: 'ibm-devops-software-engineering',
            title: 'DevOps Capstone Project',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Docker', 'Kubernetes'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SUCIDKC0FR58',
            credential: 'SUCIDKC0FR58',

            image: '/assets/courses/Coursera SUCIDKC0FR58.jpg',
        },
        {
            id: 16,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Exploratory Data Analysis for Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'EDA',
                'Python',
                'Data Visualization',
                'Feature Engineering',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SAA3BLB5E3QO',
            credential: 'SAA3BLB5E3QO',

            image: '/assets/courses/Coursera SAA3BLB5E3QO.jpg',
        },
        {
            id: 17,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Supervised Machine Learning: Regression',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Regression',
                'Linear Regression',
                'Python',
                'Scikit-learn',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/6SUJ6TU2MQNA',
            credential: '6SUJ6TU2MQNA',

            image: '/assets/courses/Coursera 6SUJ6TU2MQNA.jpg',
        },
        {
            id: 18,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Supervised Machine Learning: Classification',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Classification',
                'Logistic Regression',
                'Decision Trees',
                'SVM',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/011MJYE22PMJ',
            credential: '011MJYE22PMJ',

            image: '/assets/courses/Coursera 011MJYE22PMJ.jpg',
        },
        {
            id: 19,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Unsupervised Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Clustering', 'K-Means', 'PCA', 'Anomaly Detection'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HIMXITQQ04QJ',
            credential: 'HIMXITQQ04QJ',

            image: '/assets/courses/Coursera HIMXITQQ04QJ.jpg',
        },
        {
            id: 20,
            certificateId: 'ibm-machine-learning',
            title: 'Deep Learning and Reinforcement Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Deep Learning',
                'Reinforcement Learning',
                'Neural Networks',
                'TensorFlow',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/UQ9WUR4Q8OM6',
            credential: 'UQ9WUR4Q8OM6',

            image: '/assets/courses/Coursera UQ9WUR4Q8OM6.jpg',
        },
        {
            id: 21,
            certificateId: 'ibm-machine-learning',
            title: 'Machine Learning Capstone',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Machine Learning', 'Python', 'Capstone', 'Project'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HY9R2194EZJT',
            credential: 'HY9R2194EZJT',

            image: '/assets/courses/Coursera HY9R2194EZJT.jpg',
        },
        {
            id: 22,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Introduction to Artificial Intelligence (AI)',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Artificial Intelligence (AI)',
                'Machine Learning',
                'Deep Learning',
                'Neural Networks',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HJP3ZZUP1LZ1',
            credential: 'HJP3ZZUP1LZ1',

            image: '/assets/courses/Coursera HJP3ZZUP1LZ1.jpg',
        },
        {
            id: 23,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Generative AI: Introduction and Applications',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Generative AI',
                'Large Language Models (LLM)',
                'AI Ethics',
                'Artificial Intelligence (AI)',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SC1KGCTL9OO4',
            credential: 'SC1KGCTL9OO4',

            image: '/assets/courses/Coursera SC1KGCTL9OO4.jpg',
        },
        {
            id: 24,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Generative AI: Prompt Engineering Basics',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Prompt Engineering',
                'Generative AI',
                'ChatGPT',
                'AI Prompts',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/LD22NVUWRANC',
            credential: 'LD22NVUWRANC',

            image: '/assets/courses/Coursera LD22NVUWRANC.jpg',
        },
        {
            id: 25,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Building AI Powered Chatbots Without Programming',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Chatbots',
                'IBM Watson Assistant',
                'Conversational AI',
                'No-Code',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/L6R8H55DEA5U',
            credential: 'L6R8H55DEA5U',

            image: '/assets/courses/Coursera L6R8H55DEA5U.jpg',
        },
        {
            id: 26,
            certificateId: 'google-project-management',
            title: 'Foundations of Project Management',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Project Management',
                'Project Life Cycle',
                'Organizational Culture',
                'Project Governance',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/CNZ3FLW5RMVI',
            credential: 'CNZ3FLW5RMVI',
            image: '/assets/courses/Coursera CNZ3FLW5RMVI.jpg',
        },
        {
            id: 27,
            certificateId: 'google-project-management',
            title: 'Project Initiation: Starting a Successful Project',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Project Charter',
                'Stakeholder Analysis',
                'Project Initiation',
                'Goal Setting',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/MJ5PKEBZ2O80',
            credential: 'MJ5PKEBZ2O80',
            image: '/assets/courses/Coursera MJ5PKEBZ2O80.jpg',
        },
        {
            id: 28,
            certificateId: 'google-project-management',
            title: 'Project Planning: Putting It All Together',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Project Planning',
                'Risk Management',
                'Budgeting',
                'Work Breakdown Structure (WBS)',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/YK4EA0QGA85L',
            credential: 'YK4EA0QGA85L',
            image: '/assets/courses/Coursera YK4EA0QGA85L.jpg',
        },
        {
            id: 29,
            certificateId: 'google-project-management',
            title: 'Project Execution: Running the Project',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Project Execution',
                'Quality Management',
                'Strategic Communication',
                'Continuous Improvement',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SIC85D54ENX2',
            credential: 'SIC85D54ENX2',
            image: '/assets/courses/Coursera SIC85D54ENX2.jpg',
        },
        {
            id: 30,
            certificateId: 'google-project-management',
            title: 'Agile Project Management',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Agile Methodologies',
                'Scrum',
                'Sprint Planning',
                'Kanban',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/8YWZIJ54ERG1',
            credential: '8YWZIJ54ERG1',
            image: '/assets/courses/Coursera 8YWZIJ54ERG1.jpg',
        },
        {
            id: 31,
            certificateId: 'google-project-management',
            title: 'Capstone: Applying Project Management in the Real World',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Project Management Capstone',
                'Documentation',
                'Stakeholder Communication',
                'Problem Solving',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/P32RQCAO5HHL',
            credential: 'P32RQCAO5HHL',
            image: '/assets/courses/Coursera P32RQCAO5HHL.jpg',
        },
        {
            id: 32,
            certificateId: 'google-project-management',
            title: 'Accelerate Your Job Search with AI',
            provider: 'Google',
            issuer: 'Coursera',
            skills: [
                'Artificial Intelligence (AI)',
                'Generative AI',
                'Job Search',
                'Career Development',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/8LF8OWUFUQCQ',
            credential: '8LF8OWUFUQCQ',
            image: '/assets/courses/Coursera 8LF8OWUFUQCQ.jpg',
        },
        {
            id: 33,
            certificateId: 'applied-cryptography',
            specializationId: 'applied-cryptography',
            title: 'Cryptography and Information Theory',
            provider: 'University of Colorado System',
            issuer: 'Coursera',
            skills: [
                'Information Theory',
                'Entropy',
                'Classical Cryptography',
                'Information Security',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/T3OG0PQL7ENX',
            credential: 'T3OG0PQL7ENX',
            image: '/assets/courses/Coursera T3OG0PQL7ENX.jpg',
        },
        {
            id: 34,
            certificateId: 'applied-cryptography',
            specializationId: 'applied-cryptography',
            title: 'Symmetric Cryptography',
            provider: 'University of Colorado System',
            issuer: 'Coursera',
            skills: [
                'Symmetric Cryptography',
                'Block Ciphers',
                'Stream Ciphers',
                'AES',
                'DES',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/WO2D2QICURQ8',
            credential: 'WO2D2QICURQ8',
            image: '/assets/courses/Coursera WO2D2QICURQ8.jpg',
        },
        {
            id: 35,
            certificateId: 'applied-cryptography',
            specializationId: 'applied-cryptography',
            title: 'Asymmetric Cryptography and Key Management',
            provider: 'University of Colorado System',
            issuer: 'Coursera',
            skills: [
                'Asymmetric Cryptography',
                'Public-Key Infrastructure (PKI)',
                'RSA',
                'Key Management',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/B8P20PLR7CS9',
            credential: 'B8P20PLR7CS9',
            image: '/assets/courses/Coursera B8P20PLR7CS9.jpg',
        },
        {
            id: 36,
            certificateId: 'applied-cryptography',
            specializationId: 'applied-cryptography',
            title: 'Cryptographic Hash and Integrity Protection',
            provider: 'University of Colorado System',
            issuer: 'Coursera',
            skills: [
                'Cryptographic Hash Functions',
                'Message Authentication Codes (MAC)',
                'HMAC',
                'Digital Signatures',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/ZHVMOQ52YYAG',
            credential: 'ZHVMOQ52YYAG',
            image: '/assets/courses/Coursera ZHVMOQ52YYAG.jpg',
        },
        {
            id: 37,
            certificateId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            specializationId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'DevOps Foundation (Linux & Systems) - Hands-On',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            status: 'completed',
            skills: [
                'Linux',
                'Shell Scripting',
                'DevOps',
                'System Administration',
                'Bash',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/1B1HGIH5Q00B',
            credential: '1B1HGIH5Q00B',
            image: '/assets/courses/Coursera 1B1HGIH5Q00B.jpg',
        },
        {
            id: 38,
            certificateId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            specializationId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'Source Control & CI/CD - Hands-On',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Git',
                'GitHub',
                'CI/CD',
                'Jenkins',
                'Continuous Integration',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/source-control-ci-cd-hands-on?specialization=devops-linux-docker-kubernetes-ci-cd-iac',
            credential: '',
            image: '',
        },
        {
            id: 39,
            certificateId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            specializationId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'Mastering Docker & Containers - Hands-On Course',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Docker',
                'Containers',
                'Dockerfile',
                'Docker Compose',
                'Containerization',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/mastering-docker-containers-hands-on-course?specialization=devops-linux-docker-kubernetes-ci-cd-iac',
            credential: '',
            image: '',
        },
        {
            id: 40,
            certificateId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            specializationId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'Kubernetes Orchestration - Hands-On',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Kubernetes',
                'K8s',
                'Container Orchestration',
                'Pods',
                'Deployments',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/kubernetes-orchestration-hands-on?specialization=devops-linux-docker-kubernetes-ci-cd-iac',
            credential: '',
            image: '',
        },
        {
            id: 41,
            certificateId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            specializationId: 'devops-pro-linux-docker-kubernetes-ci-cd-iac',
            title: 'Infrastructure Automation (IaC) - Hands-On',
            provider: 'KodeKloud',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Infrastructure as Code (IaC)',
                'Terraform',
                'Ansible',
                'Automation',
                'Cloud Infrastructure',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/infrastructure-automation-iac-hands-on?specialization=devops-linux-docker-kubernetes-ci-cd-iac',
            credential: '',
            image: '',
        },
        {
            id: 42,
            certificateId: 'ibm-introduction-to-data-science',
            specializationId: 'ibm-introduction-to-data-science',
            title: 'What is Data Science?',
            provider: 'IBM',
            issuer: 'Coursera',
            status: 'completed',
            skills: [
                'Data Science',
                'Machine Learning',
                'Big Data',
                'Data Mining',
                'Deep Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/WCSV3TKT29ZN',
            credential: 'WCSV3TKT29ZN',
            image: '/assets/courses/Coursera WCSV3TKT29ZN.jpg',
        },
        {
            id: 43,
            certificateId: 'ibm-introduction-to-data-science',
            specializationId: 'ibm-introduction-to-data-science',
            title: 'Tools for Data Science',
            provider: 'IBM',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Data Science Tools',
                'Jupyter Notebook',
                'RStudio',
                'GitHub',
                'Python',
                'Watson Studio',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/open-source-tools-for-data-science?specialization=introduction-data-science',
            credential: '',
            image: '',
        },
        {
            id: 44,
            certificateId: 'ibm-introduction-to-data-science',
            specializationId: 'ibm-introduction-to-data-science',
            title: 'Data Science Methodology',
            provider: 'IBM',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'Data Science Methodology',
                'Data Understanding',
                'Data Preparation',
                'Modeling',
                'Model Evaluation',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/data-science-methodology?specialization=introduction-data-science',
            credential: '',
            image: '',
        },
        {
            id: 45,
            certificateId: 'ibm-introduction-to-data-science',
            specializationId: 'ibm-introduction-to-data-science',
            title: 'Databases and SQL for Data Science with Python',
            provider: 'IBM',
            issuer: 'Coursera',
            status: 'coming-soon',
            skills: [
                'SQL',
                'Relational Databases (RDBMS)',
                'Python',
                'SQLite',
                'Data Analysis',
            ],
            credentialUrl:
                'https://www.coursera.org/organizations/udinus/learn/sql-data-science?specialization=introduction-data-science',
            credential: '',
            image: '',
        },
    ],
};
