import type { Certificate, Course } from './types';

export const coursesData: {
    certificates: Certificate[];
    courses: Course[];
    specializations: Certificate[];
} = {
    certificates: [
        {
            id: 'ibm-machine-learning',
            title: 'IBM Machine Learning',
            category: 'Professional Certificate',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'Machine Learning',
                'Python',
                'Supervised Learning',
                'Unsupervised Learning',
                'Neural Networks',
                'Deep Learning',
                'Regression',
                'Classification',
                'Clustering',
                'Reinforcement Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/G9QD5BA2LI68',
            credential: 'G9QD5BA2LI68',
            image: '/assets/certificates/IBM Machine Learning.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'ibm-introduction-to-machine-learning',
            title: 'IBM Introduction to Machine Learning',
            category: 'Specialization',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'Machine Learning',
                'Exploratory Data Analysis',
                'Supervised Learning',
                'Unsupervised Learning',
                'Linear Regression',
                'Classification',
                'Python',
                'Scikit-learn',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/specialization/C1ITBGE5WI0Z',
            credential: 'C1ITBGE5WI0Z',
            image: '/assets/certificates/IBM Introduction to Machine Learning.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
                {
            id: 'ibm-devops-software-engineering',
            title: 'IBM DevOps and Software Engineering',
            category: 'Professional Certificate',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-05-18',
            skills: [
                'DevOps',
                'Software Engineering',
                'CI/CD',
                'Agile Methodologies',
                'Linux',
                'Git',
                'Docker',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/1OVGPIEULHS5',
            credential: '1OVGPIEULHS5',
            image: '/assets/certificates/IBM DevOps and Software Engineering.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'ibm-ai-foundations-for-everyone',
            title: 'AI Foundations for Everyone',
            category: 'Specialization',
            provider: 'IBM',
            issuer: 'Coursera',
            date: '2026-09-25',
            skills: [
                'Artificial Intelligence (AI)',
                'Generative AI',
                'Prompt Engineering',
                'Chatbots',
                'IBM Watson',
                'Machine Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/specialization/7VNLDPYRA9M2',
            credential: '7VNLDPYRA9M2',
            image: '/assets/certificates/IBM AI Foundations for Everyone Specialization.jpg',
            logo: '/assets/images/logo/ibm.svg',
        },
        {
            id: 'pimnas-peserta',
            title: 'Peserta Pekan Ilmiah Mahasiswa Nasional (PIMNAS) 2025',
            category: 'Competition & Award',
            provider: 'Kemdiktisaintek',
            issuer: 'Belmawa',
            date: '2025-12-04',
            skills: [
                'PKM-KI',
                'Kesehatan',
                'IoT',
                'Penelitian',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/PESERTA-PIMNAS.jpg',
            logo: '/assets/images/logo/Ministry_of_Education_and_Culture_of_Republic_of_Indonesia.svg',
        },
        {
            id: 'pimnas-pendanaan',
            title: 'Peraih Pendanaan & Finalis PIMNAS PKM-KI 2025',
            category: 'Competition & Award',
            provider: 'Kemdiktisaintek',
            issuer: 'Belmawa',
            date: '2025-12-04',
            skills: [
                'PKM-KI',
                'Karya Inovatif',
                'Pendanaan',
                'Penelitian',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/PENDANAAN-PKM.jpg',
            logo: '/assets/images/logo/Ministry_of_Education_and_Culture_of_Republic_of_Indonesia.svg',
        },
        {
            id: 'bnsp-web-developer',
            title: 'Sertifikat Kompetensi – Web Developer',
            category: 'Competency Certification',
            provider: 'Badan Nasional Sertifikasi Profesi (BNSP)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2025-01-28',
            skills: [
                'Web Programming',
                'Frontend',
                'Backend',
                'Sertifikasi BNSP',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/bnsp-web-developer.png',
            logo: '/assets/images/logo/logo-bnsp.png',
        },
        {
            id: 'bnsp-junior-mobile-programmer',
            title: 'Sertifikat Kompetensi – Junior Mobile Programmer',
            category: 'Competency Certification',
            provider: 'Badan Nasional Sertifikasi Profesi (BNSP)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2024-09-17',
            skills: [
                'Mobile Programming',
                'Kotlin',
                'Android',
                'Sertifikasi BNSP',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/bnsp-junior-mobile-developer.png',
            logo: '/assets/images/logo/logo-bnsp.png',
        },
        {
            id: 'apti-pemrograman-web',
            title: 'Sertifikat Kompetensi Keahlian – Pemrograman Web',
            category: 'Competency Certification',
            provider: 'Asosiasi Profesi Telematika Indonesia (APTI)',
            issuer: 'LSP Universitas Dian Nuswantoro',
            date: '2024-01-22',
            skills: [
                'Web Programming',
                'Frontend',
                'Backend',
                'Sertifikasi APTI',
            ],
            credentialUrl: '#',
            credential: '',
            image: '/assets/certificates/apti-web-programming.png',
            logo: '/assets/images/logo/logo-apti.png',
        },
    ],
    get specializations() {
        return this.certificates;
    },
    courses: [
        {
            id: 1,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Agile'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/PUUPJRYMVFWY',
            credential: 'PUUPJRYMVFWY',
            image: '#',
        },
        {
            id: 2,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Cloud Computing',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Cloud Computing', 'IaaS', 'PaaS', 'SaaS'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/KWII2E29GUCP',
            credential: 'KWII2E29GUCP',
            image: '#',
        },
        {
            id: 3,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Agile Development and Scrum',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Agile', 'Scrum', 'Sprint Planning', 'Kanban'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/B58WYKB58HX3',
            credential: 'B58WYKB58HX3',
            image: '#',
        },
        {
            id: 4,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Software Engineering',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Software Engineering', 'SDLC', 'UML', 'Design Patterns'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/9YNVBW6VFS74',
            credential: '9YNVBW6VFS74',
            image: '#',
        },
        {
            id: 5,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Getting Started with Git and GitHub',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Git', 'GitHub', 'Version Control', 'Branching'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/QU0UD8JBBN5Y',
            credential: 'QU0UD8JBBN5Y',
            image: '#',
        },
        {
            id: 6,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Hands-on Introduction to Linux Commands and Shell Scripting',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Linux', 'Shell Scripting', 'Bash', 'Command Line'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/NTXSWHCXGP3M',
            credential: 'NTXSWHCXGP3M',
            image: '#',
        },
        {
            id: 7,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Python for Data Science, AI & Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Data Science', 'Pandas', 'NumPy'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/00CUZNBVXHAY',
            credential: '00CUZNBVXHAY',
            image: '#',
        },
        {
            id: 8,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Developing AI Applications with Python and Flask',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Flask', 'REST API', 'AI'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/N0Y5ATDNQA8A',
            credential: 'N0Y5ATDNQA8A',
            image: '#',
        },
        {
            id: 9,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Containers w/ Docker, Kubernetes & OpenShift',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Docker', 'Kubernetes', 'OpenShift', 'Containers'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/X9VP7V6B22F2',
            credential: 'X9VP7V6B22F2',
            image: '#',
        },
        {
            id: 10,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Application Development using Microservices and Serverless',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Microservices', 'Serverless', 'REST API', 'Cloud Native'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/9ZP2USR1M7WN',
            credential: '9ZP2USR1M7WN',
            image: '#',
        },
        {
            id: 11,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Introduction to Test and Behavior Driven Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['TDD', 'BDD', 'Testing', 'Python'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/COIY4WLZRL9Q',
            credential: 'COIY4WLZRL9Q',
            image: '#',
        },
        {
            id: 12,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Continuous Integration and Continuous Delivery (CI/CD)',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['CI/CD', 'Jenkins', 'DevOps', 'Automation'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/TKS66EQVG4WU',
            credential: 'TKS66EQVG4WU',
            image: '#',
        },
        {
            id: 13,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Application Security for Developers and DevOps Professionals',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Security', 'DevSecOps', 'OWASP', 'Threat Modeling'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/GN3SHQZ0PIQT',
            credential: 'GN3SHQZ0PIQT',
            image: '#',
        },
        {
            id: 14,
            certificateId: 'ibm-devops-software-engineering',
            title: 'Monitoring and Observability for Development and DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Monitoring', 'Observability', 'Prometheus', 'Grafana'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/IOTESW68DTO6',
            credential: 'IOTESW68DTO6',
            image: '#',
        },
        {
            id: 15,
            certificateId: 'ibm-devops-software-engineering',
            title: 'DevOps Capstone Project',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Docker', 'Kubernetes'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SUCIDKC0FR58',
            credential: 'SUCIDKC0FR58',
            image: '#',
        },
        {
            id: 16,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Exploratory Data Analysis for Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'EDA',
                'Python',
                'Data Visualization',
                'Feature Engineering',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SAA3BLB5E3QO',
            credential: 'SAA3BLB5E3QO',
            image: '#',
        },
        {
            id: 17,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Supervised Machine Learning: Regression',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Regression',
                'Linear Regression',
                'Python',
                'Scikit-learn',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/6SUJ6TU2MQNA',
            credential: '6SUJ6TU2MQNA',
            image: '#',
        },
        {
            id: 18,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Supervised Machine Learning: Classification',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Classification',
                'Logistic Regression',
                'Decision Trees',
                'SVM',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/011MJYE22PMJ',
            credential: '011MJYE22PMJ',
            image: '#',
        },
        {
            id: 19,
            certificateId: 'ibm-machine-learning',
            specializationId: 'ibm-introduction-to-machine-learning',
            title: 'Unsupervised Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Clustering', 'K-Means', 'PCA', 'Anomaly Detection'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HIMXITQQ04QJ',
            credential: 'HIMXITQQ04QJ',
            image: '#',
        },
        {
            id: 20,
            certificateId: 'ibm-machine-learning',
            title: 'Deep Learning and Reinforcement Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Deep Learning',
                'Reinforcement Learning',
                'Neural Networks',
                'TensorFlow',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/UQ9WUR4Q8OM6',
            credential: 'UQ9WUR4Q8OM6',
            image: '#',
        },
        {
            id: 21,
            certificateId: 'ibm-machine-learning',
            title: 'Machine Learning Capstone',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Machine Learning', 'Python', 'Capstone', 'Project'],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HY9R2194EZJT',
            credential: 'HY9R2194EZJT',
            image: '#',
        },
        {
            id: 22,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Introduction to Artificial Intelligence (AI)',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Artificial Intelligence (AI)',
                'Machine Learning',
                'Deep Learning',
                'Neural Networks',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/HJP3ZZUP1LZ1',
            credential: 'HJP3ZZUP1LZ1',
            image: '#',
        },
        {
            id: 23,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Generative AI: Introduction and Applications',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Generative AI',
                'Large Language Models (LLM)',
                'AI Ethics',
                'Artificial Intelligence (AI)',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/SC1KGCTL9OO4',
            credential: 'SC1KGCTL9OO4',
            image: '#',
        },
        {
            id: 24,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Generative AI: Prompt Engineering Basics',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Prompt Engineering',
                'Generative AI',
                'ChatGPT',
                'AI Prompts',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/LD22NVUWRANC',
            credential: 'LD22NVUWRANC',
            image: '#',
        },
        {
            id: 25,
            certificateId: 'ibm-ai-foundations-for-everyone',
            title: 'Building AI Powered Chatbots Without Programming',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Chatbots',
                'IBM Watson Assistant',
                'Conversational AI',
                'No-Code',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/verify/L6R8H55DEA5U',
            credential: 'L6R8H55DEA5U',
            image: '#',
        },
    ],
};
