import type { Project } from './types';

export const projects: Project[] = [
    {
        id: 'renstra-ft',
        image: '/assets/images/projects/project-renstra-login.png',
        gallery: [
            '/assets/images/projects/project-renstra-login.png',
            '/assets/images/projects/project-renstra.png',
            '/assets/images/projects/project-renstra-hasil.png',
        ],
        title: 'RENSTRA FT',
        type: 'Team',
        privacy: 'Private',
        cardDesc:
            'Information System for Strategic Plan (RENSTRA) for monitoring and reporting Key Performance Indicators (KPI/IKU) and lecturer workload (EWMP).',
        desc: 'Information System for Strategic Plan (RENSTRA) for monitoring and reporting Key Performance Indicators (KPI/IKU) and lecturer workload (EWMP). Facilitates the university in monitoring annual target achievements. The dashboard provides clear visualizations of progress against multi-year strategic goals, allowing faculty leadership to make data-driven decisions and adjust operational tactics when specific targets fall behind schedule.',
        role: 'Backend Developer',
        year: '2024',
        websiteType: 'Information System',
        sector: 'Academic',
        tags: ['CodeIgniter', 'PHP', 'Bootstrap', 'MySQL'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/renstra_ftdinus',
    },
    {
        id: 'portfolio-ft',
        image: '/assets/images/projects/project-portofolio-login.png',
        gallery: [
            '/assets/images/projects/project-portofolio-login.png',
            '/assets/images/projects/project-portofolio-riwayat.png',
            '/assets/images/projects/project-portofolio-form.png',
        ],
        title: 'Portfolio MK FT',
        type: 'Team',
        privacy: 'Private',
        cardDesc:
            'Management and documentation system for the entire academic cycle of FT courses.',
        desc: 'Management and documentation system for the entire academic cycle of FT courses. Enables tracking of syllabi, course materials, and assignments in one integrated platform for lecturers and students. The platform standardizes the course documentation process across the Engineering Faculty, ensuring that all course materials are centrally stored, easily accessible, and properly versioned for accreditation purposes.',
        role: 'Backend Developer',
        year: '2025',
        websiteType: 'Information System',
        sector: 'Academic',
        tags: ['CodeIgniter', 'PHP', 'Bootstrap', 'MySQL'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/portofolio-ftdinus',
    },
    {
        id: 'medical-checkup-ft',
        image: '/assets/images/projects/project-medical-login.png',
        gallery: [
            '/assets/images/projects/project-medical-login.png',
            '/assets/images/projects/project-medical-dashboard.png',
            '/assets/images/projects/project-medical-view-pasien.png',
            '/assets/images/projects/project-medical-data-periksa.png',
        ],
        title: 'Medical Checkup FT',
        type: 'Team',
        privacy: 'Private',
        cardDesc:
            'A healthcare management platform integrated with IoT-based self-service health kiosks for monitoring and recording patient health data.',
        desc: 'A web-based healthcare management system developed to support Anjungan Kesehatan Mandiri (Independent Health Kiosks) using IoT technology. Health data collected through the kiosks is transmitted via API and stored within the platform for monitoring, analysis, and reporting. This project was a collaborative initiative between FT Universitas Dian Nuswantoro and the Semarang Health Department to enhance digital healthcare services and improve public access to health monitoring.',
        role: 'Backend & API Developer',
        year: '2024',
        websiteType: 'Information System',
        sector: 'Healthcare',
        tags: ['CodeIgniter', 'PHP', 'IoT', 'MySQL'],
        demo: '',
        github: 'https://github.com/Alfaturachman/ftdinus_medical',
    },
    {
        id: 'atr-bpn-jateng',
        image: '/assets/images/projects/project-bpn-jateng-home.png',
        gallery: [
            '/assets/images/projects/project-bpn-jateng-home.png',
            '/assets/images/projects/project-bpn-jateng-login.png',
            '/assets/images/projects/project-bpn-jateng-surat.png',
        ],
        title: 'ATR/BPN Jateng',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'A web portal for ATR/BPN Central Java featuring an administrative system for managing incoming/outgoing letters and disposition workflows.',
        desc: 'A web portal for the Regional Office of ATR/BPN Central Java. It features a comprehensive administrative system for managing incoming and outgoing letters, tracking disposition workflows, scheduling agendas, and distributing public information. This system significantly improves the efficiency of internal administrative processes and provides better public access to land-related information in Central Java.',
        role: 'Full-Stack Developer',
        year: '2024',
        websiteType: 'Web Portal',
        sector: 'Government',
        tags: ['CodeIgniter', 'PHP', 'MySQL', 'Bootstrap', 'jQuery'],
        demo: 'https://www.atrbpn-jateng.com/',
        github: 'https://github.com/Alfaturachman/atrbpn-jateng',
    },
    {
        id: 'crumb-rubber',
        image: '/assets/images/projects/project-rubber-home.png',
        gallery: [
            '/assets/images/projects/project-rubber-home.png',
            '/assets/images/projects/project-rubber-login.png',
            '/assets/images/projects/project-rubber-dashboard.png',
            '/assets/images/projects/project-rubber-mitra.png',
            '/assets/images/projects/project-rubber-stok.png',
        ],
        title: 'Crumb Rubber',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'Inventory management system for the crumb rubber industry, including raw material recording, processed products, and reports.',
        desc: 'Inventory management system for the crumb rubber industry, including raw material recording, processed products, and real-time stock reports to improve factory operational efficiency. The system tracks the entire production lifecycle from the intake of raw rubber materials, through processing stages, to the final crumb rubber products ready for shipping.',
        role: 'Full-Stack Developer',
        year: '2023',
        websiteType: 'Information System',
        sector: 'Manufacturing',
        tags: ['CodeIgniter', 'PHP', 'REST API', 'MySQL'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/crumb-rubber',
    },
    {
        id: 'iconnet-monitoring',
        image: '/assets/images/projects/project-iconnet-home.png',
        gallery: [
            '/assets/images/projects/project-iconnet-home.png',
            '/assets/images/projects/project-iconnet-login.png',
            '/assets/images/projects/project-iconnet-langganan.png',
        ],
        title: 'Iconnet Monitoring',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'Iconnet monitoring application for tracking and recording Iconnet service outage reports.',
        desc: 'A web-based monitoring system for Iconnet services that enables users to report service disruptions and allows technicians to track, manage, and resolve those reports efficiently. The system features a user-friendly dashboard for monitoring the status of outage reports in real-time, complete with notification workflows and historical reporting for service performance analysis.',
        role: 'Full-Stack Developer',
        year: '2024',
        websiteType: 'Monitoring System',
        sector: 'Corporate',
        tags: ['CodeIgniter', 'PHP', 'Bootstrap', 'REST API', 'MySQL'],
        demo: '',
        github: 'https://github.com/Alfaturachman/iconnet-monitoring',
    },
    {
        id: 'disnaker-agenda',
        image: '/assets/images/projects/project-disnaker-agenda-mediasi-login.png',
        gallery: [
            '/assets/images/projects/project-disnaker-agenda-mediasi-login.png',
            '/assets/images/projects/project-disnaker-agenda-mediasi-home.png',
            '/assets/images/projects/project-disnaker-agenda-mediasi-riwayat.png',
        ],
        title: 'Disnaker Agenda Mediasi',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'Agenda Mediasi application for managing and scheduling mediation sessions at the Manpower Office (Disnaker).',
        desc: 'A web-based agenda mediation system for the Manpower Office (Disnaker) to manage the scheduling, recording, and tracking of mediation sessions between workers and employers. Streamlines the mediation process with digital records, status tracking, and report generation.',
        role: 'Full-Stack Developer',
        year: '2025',
        websiteType: 'Information System',
        sector: 'Government',
        tags: ['CodeIgniter', 'PHP', 'MySQL', 'Bootstrap', 'jQuery'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/disnaker_agenda',
    },
    {
        id: 'disnaker-monitoring',
        image: '/assets/images/projects/project-disnaker-monitoring-login.png',
        gallery: [
            '/assets/images/projects/project-disnaker-monitoring-login.png',
            '/assets/images/projects/project-disnaker-monitoring-home.png',
            '/assets/images/projects/project-disnaker-monitoring-berita.png',
        ],
        title: 'Disnaker Monitoring Berita',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'A web-based application for media monitoring and information management developed for the Manpower Office (Disnaker).',
        desc: 'A web-based application for media monitoring and information management developed for the Manpower Office (Disnaker). This system allows users to monitor media coverage, track trends, and generate reports. It features keyword tracking and sentiment analysis categorization to help the public relations team respond effectively to emerging issues.',
        role: 'Full-Stack Developer',
        year: '2025',
        websiteType: 'Monitoring System',
        sector: 'Government',
        tags: ['CodeIgniter', 'PHP', 'MySQL', 'Bootstrap', 'jQuery'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/disnaker_monitoring',
    },
    {
        id: 'stedi',
        image: '/assets/images/projects/project-stedi-login.png',
        gallery: [
            '/assets/images/projects/project-stedi-login.png',
            '/assets/images/projects/project-stedi-diagnosa.png',
            '/assets/images/projects/project-stedi-pasien.png',
        ],
        title: 'STEDI Digital Stethoscope',
        type: 'Team',
        privacy: 'Private',
        cardDesc:
            'STEDI is a medical device that can record lung sounds and analyze them using artificial intelligence to assist in diagnosis.',
        desc: 'STEDI is a medical device that can record lung sounds and analyze them using artificial intelligence. This system is expected to help doctors diagnose lung diseases more quickly and accurately using deep learning models.',
        role: 'AI & Backend Developer',
        year: '2025',
        websiteType: 'AI Web App',
        sector: 'Healthcare',
        tags: ['Python', 'Django', 'Keras', 'Firebase', 'IoT'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/stediwave',
    },
    {
        id: 'posyandu',
        image: '/assets/images/projects/project-egrowth-home.png',
        gallery: [
            '/assets/images/projects/project-egrowth-home.png',
            '/assets/images/projects/project-egrowth-login.png',
            '/assets/images/projects/project-egrowth-detail.png',
        ],
        title: 'Posyandu Information System',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'Posyandu information system for recording toddler development and immunization schedules, replacing the manual pink book.',
        desc: "A web-based Posyandu information system built with Laravel PHP to digitize toddler growth and immunization records. Every week, children's immunizations and developmental progress are recorded — replacing the traditional pink book (Buku Pink) system with a fully digital, searchable, and reportable database.",
        role: 'Full-Stack Developer',
        year: '2025',
        websiteType: 'Information System',
        sector: 'Healthcare',
        tags: ['Laravel', 'PHP', 'MySQL', 'Bootstrap'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/sistem-posyandu',
    },
    {
        id: 'nomadenstuff',
        image: '/assets/images/projects/project-nomadenstuff-home.png',
        gallery: [
            '/assets/images/projects/project-nomadenstuff-home.png',
            '/assets/images/projects/project-nomadenstuff-shop.png',
            '/assets/images/projects/project-nomadenstuff-cart.png',
            '/assets/images/projects/project-nomadenstuff-history.png',
        ],
        title: 'NomadenStuff Ecommerce',
        type: 'Freelance',
        privacy: 'Public',
        cardDesc:
            'NomadenStuff Ecommerce is an e-commerce application for thrift shop.',
        desc: 'NomadenStuff Ecommerce is a specialized e-commerce application built for a thrift shop business. The platform manages unique, single-item inventory typical in thrifting, offering features like product reservations, detailed sizing guides, and automated shipping calculations.',
        role: 'Full-Stack Developer',
        year: '2023',
        websiteType: 'E-Commerce',
        sector: 'Retail',
        tags: ['CodeIgniter', 'PHP', 'MySQL', 'Bootstrap', 'jQuery'],
        demo: '#',
        github: 'https://github.com/Alfaturachman/nomadenstuff_ecommerce',
    },
    {
        id: 'pusdataru-jateng',
        image: '/assets/images/projects/project-pusdataru-home.png',
        gallery: [
            '/assets/images/projects/project-pusdataru-login.png',
            '/assets/images/projects/project-pusdataru-home.png',
            '/assets/images/projects/project-pusdataru-pengaduan.png',
        ],
        title: 'Pusdataru Jateng',
        type: 'Freelance',
        privacy: 'Private',
        cardDesc:
            'Public complaint management information system for the province of Central Java.',
        desc: 'A web-based complaint management information system for the province of Central Java (Pusdataru Jateng) that allows citizens to submit, track, and manage public complaints digitally. Built with Laravel and MySQL, the system streamlines the workflow from complaint submission through verification, assignment to relevant departments, and resolution tracking.',
        role: 'Full-Stack Developer',
        year: '2025',
        websiteType: 'Information System',
        sector: 'Government',
        tags: ['Laravel', 'PHP', 'MySQL', 'Bootstrap'],
        demo: '#',
        github: '#',
    },
    {
        id: 'kireikies',
        image: '/assets/images/projects/project-kireikies-menu.png',
        gallery: ['/assets/images/projects/project-kireikies-menu.png'],
        title: 'Kireikies Cookies Website',
        type: 'Freelance',
        privacy: 'Public',
        cardDesc:
            'Website for Kireikies Cookies store, showcasing product catalog and store information.',
        desc: 'Website for Kireikies Cookies store, showcasing product catalog and store information. This project was built with a focus on clean UI and smooth user experience to enhance artisan product branding.',
        role: 'Frontend Developer',
        year: '2026',
        websiteType: 'Landing Page',
        sector: 'Retail',
        tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
        demo: 'https://kireikies-cookies.vercel.app/',
        github: 'https://github.com/Alfaturachman/kireikies-cookies',
    },
];
