import type { Specialization, Course } from './types';

export const coursesData: {
    specializations: Specialization[];
    courses: Course[];
} = {
    specializations: [
        {
            id: 1,
            title: 'IBM DevOps and Software Engineering',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'DevOps',
                'Software Engineering',
                'CI/CD',
                'Agile Methodologies',
                'Linux',
                'Git',
                'Docker',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/1OVGPIEULHS5',
            credential: '1OVGPIEULHS5',
            image: '/assets/certificate/Specializations/IBM DevOps and Software Engineering.jpg',
        },
        {
            id: 2,
            title: 'IBM Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Machine Learning',
                'Python',
                'Supervised Learning',
                'Unsupervised Learning',
                'Neural Networks',
                'Deep Learning',
                'Regression',
                'Classification',
                'Clustering',
                'Reinforcement Learning',
            ],
            credentialUrl:
                'https://www.coursera.org/account/accomplishments/professional-cert/G9QD5BA2LI68',
            credential: 'G9QD5BA2LI68',
            image: '/assets/certificate/Specializations/IBM Machine Learning.jpg',
        },
    ],
    courses: [
        {
            id: 1,
            specializationId: 1,
            title: 'Introduction to DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Agile'],
            credentialUrl:
                'https://www.coursera.org/account/credentials/specialization/AC7L7Y74D66X',
            credential: 'AC7L7Y74D66X',
            image: '#',
        },
        {
            id: 2,
            specializationId: 1,
            title: 'Introduction to Cloud Computing',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Cloud Computing', 'IaaS', 'PaaS', 'SaaS'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 3,
            specializationId: 1,
            title: 'Introduction to Agile Development and Scrum',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Agile', 'Scrum', 'Sprint Planning', 'Kanban'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 4,
            specializationId: 1,
            title: 'Introduction to Software Engineering',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Software Engineering', 'SDLC', 'UML', 'Design Patterns'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 5,
            specializationId: 1,
            title: 'Getting Started with Git and GitHub',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Git', 'GitHub', 'Version Control', 'Branching'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 6,
            specializationId: 1,
            title: 'Hands-on Introduction to Linux Commands and Shell Scripting',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Linux', 'Shell Scripting', 'Bash', 'Command Line'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 7,
            specializationId: 1,
            title: 'Python for Data Science, AI & Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Data Science', 'Pandas', 'NumPy'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 8,
            specializationId: 1,
            title: 'Developing AI Applications with Python and Flask',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Python', 'Flask', 'REST API', 'AI'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 9,
            specializationId: 1,
            title: 'Introduction to Containers w/ Docker, Kubernetes & OpenShift',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Docker', 'Kubernetes', 'OpenShift', 'Containers'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 10,
            specializationId: 1,
            title: 'Application Development using Microservices and Serverless',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Microservices', 'Serverless', 'REST API', 'Cloud Native'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 11,
            specializationId: 1,
            title: 'Introduction to Test and Behavior Driven Development',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['TDD', 'BDD', 'Testing', 'Python'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 12,
            specializationId: 1,
            title: 'Continuous Integration and Continuous Delivery (CI/CD)',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['CI/CD', 'Jenkins', 'DevOps', 'Automation'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 13,
            specializationId: 1,
            title: 'Application Security for Developers and DevOps Professionals',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Security', 'DevSecOps', 'OWASP', 'Threat Modeling'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 14,
            specializationId: 1,
            title: 'Monitoring and Observability for Development and DevOps',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Monitoring', 'Observability', 'Prometheus', 'Grafana'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 15,
            specializationId: 1,
            title: 'DevOps Capstone Project',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['DevOps', 'CI/CD', 'Docker', 'Kubernetes'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 16,
            specializationId: 2,
            title: 'Exploratory Data Analysis for Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'EDA',
                'Python',
                'Data Visualization',
                'Feature Engineering',
            ],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 17,
            specializationId: 2,
            title: 'Supervised Machine Learning: Regression',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Regression',
                'Linear Regression',
                'Python',
                'Scikit-learn',
            ],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 18,
            specializationId: 2,
            title: 'Supervised Machine Learning: Classification',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Classification',
                'Logistic Regression',
                'Decision Trees',
                'SVM',
            ],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 19,
            specializationId: 2,
            title: 'Unsupervised Machine Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Clustering', 'K-Means', 'PCA', 'Anomaly Detection'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 20,
            specializationId: 2,
            title: 'Deep Learning and Reinforcement Learning',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: [
                'Deep Learning',
                'Reinforcement Learning',
                'Neural Networks',
                'TensorFlow',
            ],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
        {
            id: 21,
            specializationId: 2,
            title: 'Machine Learning Capstone',
            provider: 'IBM',
            issuer: 'Coursera',
            skills: ['Machine Learning', 'Python', 'Capstone', 'Project'],
            credentialUrl: '#',
            credential: '#',
            image: '#',
        },
    ],
};
